version: "3"

services:
  db:
    image: mongo
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    volumes:
      - data-volume:/data/db
  db-service:
    build: ./db-service
    env_file:
      - .env
    ports:
      - ${DB_SERVICE_PORT}:${DB_SERVICE_PORT}
    depends_on:
      - db
    volumes:
      - ./db-service/src:/app/db-service/src
    restart: always
  bff:
      build: ./bff
      env_file:
        - .env
      ports:
        - ${BFF_PORT}:${BFF_PORT}
      command: npm run start
      depends_on:
        - db-service
      volumes:
        - ./bff/src:/app/bff/src
      restart: always
volumes:
  data-volume: