version: "3"

services:
  db:
    image: mongo
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    volumes:
      - data-volume:/data/db

  seed-service:
    build: ./seed-service
    env_file:
      - .env
    ports:
      - ${SEED_SERVICE_PORT}:${SEED_SERVICE_PORT}
    depends_on:
      - db
    volumes:
      - ./seed-service/src:/app/seed-service/src
    restart: always

  users-service:
    build: ./users-service
    env_file:
      - .env
    ports:
      - ${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}
    depends_on:
      - db
    volumes:
      - ./users-service/src:/app/users-service/src
    restart: always

  companies-service:
    build: ./companies-service
    env_file:
      - .env
    ports:
      - ${COMPANIES_SERVICE_PORT}:${COMPANIES_SERVICE_PORT}
    depends_on:
      - db
    volumes:
      - ./companies-service/src:/app/companies-service/src
    restart: always

  vacancies-service:
    build: ./vacancies-service
    env_file:
      - .env
    ports:
      - ${VACANCIES_SERVICE_PORT}:${VACANCIES_SERVICE_PORT}
    depends_on:
      - db
    volumes:
      - ./vacancies-service/src:/app/vacancies-service/src
    restart: always

  bff:
      build: ./bff
      env_file:
        - .env
      ports:
        - ${BFF_PORT}:${BFF_PORT}
      command: npm run start
      depends_on:
        - seed-service
        - users-service
        - companies-service
        - vacancies-service
      volumes:
        - ./bff/src:/app/bff/src
      restart: always

volumes:
  data-volume: